### PR TITLE
Small change to simplify instructions for Windows users

### LINKED ISSUE #5: [Documentation] for running on windows can be simplified
It's not necessary to explicitly list the folder path for volume mapping on Windows, the ${PWD} token can be used

### PR DESCRIPTION
**Pull request by gavinbarron**
Resolves #5

### CODE REVIEW

**Comment by waldekmastykarz** [comment]
Thanks for the suggestion @gavinbarron! Is the `${PWD}` token specific to a certain terminal, like cmder or PowerShell or does it work universally, including the regular Windows command prompts?

**Comment by gavinbarron** [comment]
It works for PowerShell, not in CMD or cmder. If you want I can adjust the PR to have a PowerShell specific instruction and retain the existing as for other (less advanced) windows shells

**Comment by waldekmastykarz** [comment]
Please do, that would be the best for clarity. I'll then merge the PR 👍

**Comment by gavinbarron** [comment]
Updated :)

**Comment by waldekmastykarz** [comment]
And merged (manually)! Thanks again Gavin!

**Pull request closed without merging**
